name: Deploy to production

on:
  push:
    branches:
      - "main"

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install AWS CDK
        run: npm install aws-cdk

      - name: Set up application
        run: |
          pip install -r requirements.txt
          cd frontend
          npm install
          npm run build

      - name: Deploy
        run: npx cdk deploy --require-approval=never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
